/* Product catalog + tag weights used by the quiz matcher.
   Prices are in AUD, per single vial — converted from the supplier's
   USD wholesale box pricing (lowest available box-quantity tier ÷ 10
   vials/box, converted at ~1 USD = 1.38 AUD).
   tags: category -> relevance weight (0-3), used by the Q&A matcher. */
const PRODUCTS = [
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    icon: "⚖️",
    tagline: "Dual GIP/GLP-1 metabolic research",
    description: "A dual GIP/GLP-1 receptor agonist widely studied in metabolic and weight-management research models.",
    tags: { weight: 3 },
    sizes: [
      { code: "TR10", spec: "10mg/vial", price: 8 },
      { code: "TR15", spec: "15mg/vial", price: 10 },
      { code: "TR20", spec: "20mg/vial", price: 13 },
      { code: "TR30", spec: "30mg/vial", price: 16 },
      { code: "TR40", spec: "40mg/vial", price: 17 },
      { code: "TR50", spec: "50mg/vial", price: 21 },
      { code: "TR60", spec: "60mg/vial", price: 24 },
      { code: "TR80", spec: "80mg/vial", price: 28 },
      { code: "TR120", spec: "120mg/vial", price: 34 },
    ],
  },
  {
    id: "retatrutide",
    name: "Retatrutide",
    icon: "⚖️",
    tagline: "Triple-agonist metabolic research",
    description: "A GIP/GLP-1/glucagon triple receptor agonist studied for its effects on metabolic rate and weight in research models.",
    tags: { weight: 3 },
    sizes: [
      { code: "RT10", spec: "10mg/vial", price: 14 },
      { code: "RT15", spec: "15mg/vial", price: 17 },
      { code: "RT20", spec: "20mg/vial", price: 20 },
      { code: "RT30", spec: "30mg/vial", price: 23 },
      { code: "RT40", spec: "40mg/vial", price: 27 },
      { code: "RT60", spec: "60mg/vial", price: 38 },
    ],
  },
  {
    id: "cagrilintide",
    name: "CagriLintide",
    icon: "⚖️",
    tagline: "Amylin-analog weight research",
    description: "A long-acting amylin analog studied for its role in appetite regulation and weight-management research, often alongside GLP-1 research.",
    tags: { weight: 2 },
    sizes: [
      { code: "CGL5", spec: "5mg/vial", price: 12 },
      { code: "CGL10", spec: "10mg/vial", price: 20 },
    ],
  },
  {
    id: "aod-9604",
    name: "AOD-9604",
    icon: "⚖️",
    tagline: "Metabolism & weight research",
    description: "A modified fragment of human growth hormone studied for its targeted effects on fat metabolism in research models.",
    tags: { weight: 3 },
    sizes: [{ code: "AOD5", spec: "5mg/vial", price: 14 }],
  },
  {
    id: "tesamorelin",
    name: "Tesamorelin",
    icon: "🏋️",
    tagline: "GH-releasing hormone research",
    description: "A growth-hormone releasing hormone analog studied for its effects on visceral fat and lean mass in research models.",
    tags: { weight: 2, muscle: 2 },
    sizes: [
      { code: "TSM5", spec: "5mg/vial", price: 13 },
      { code: "TSM10", spec: "10mg/vial", price: 20 },
      { code: "TSM20", spec: "20mg/vial", price: 39 },
    ],
  },
  {
    id: "mots-c",
    name: "MOTS-c",
    icon: "🔋",
    tagline: "Mitochondrial & metabolic research",
    description: "A mitochondrial-derived peptide studied for its role in metabolic regulation and exercise-response research.",
    tags: { weight: 2, muscle: 1, antiaging: 1 },
    sizes: [
      { code: "MS10", spec: "10mg/vial", price: 9 },
      { code: "MS20", spec: "20mg/vial", price: 15 },
      { code: "MS40", spec: "40mg/vial", price: 23 },
    ],
  },
  {
    id: "lemon-bottle",
    name: "Lemon Bottle",
    icon: "🍋",
    tagline: "Body-contouring research blend",
    description: "A plant-extract blend (pineapple/Ananas Sativus, bromelain, scutellaria baicalensis, centella asiatica and more) studied in body-contouring and fat-reduction research.",
    tags: { skin: 2, weight: 2 },
    sizes: [{ code: "LB10", spec: "10mg/vial", price: 10 }],
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    icon: "⚖️",
    tagline: "GLP-1 metabolic research",
    description: "A GLP-1 receptor agonist widely studied in metabolic, appetite, and weight-management research models.",
    tags: { weight: 3 },
    sizes: [
      { code: "SM10", spec: "10mg/vial", price: 5 },
      { code: "SM15", spec: "15mg/vial", price: 7 },
      { code: "SM20", spec: "20mg/vial", price: 8 },
      { code: "SM30", spec: "30mg/vial", price: 10 },
    ],
  },
  {
    id: "nad",
    name: "NAD+",
    icon: "🔋",
    tagline: "Cellular energy & longevity research",
    description: "A coenzyme central to cellular energy metabolism, widely studied in longevity and mitochondrial-function research.",
    tags: { antiaging: 2, recovery: 1 },
    sizes: [
      { code: "NJ100", spec: "100mg/vial", price: 6 },
      { code: "NJ500", spec: "500mg/vial", price: 10 },
      { code: "NJ1000", spec: "1000mg/vial", price: 14 },
    ],
  },
  {
    id: "epithalon",
    name: "Epithalon",
    icon: "🌙",
    tagline: "Longevity & sleep-cycle research",
    description: "A synthetic tetrapeptide studied for its role in telomerase activity and circadian rhythm regulation in longevity research.",
    tags: { antiaging: 3, sleep: 2 },
    sizes: [
      { code: "ET10", spec: "10mg/vial", price: 7 },
      { code: "ET50", spec: "50mg/vial", price: 20 },
    ],
  },
  {
    id: "ss-31",
    name: "SS-31",
    icon: "🔋",
    tagline: "Mitochondrial antioxidant research",
    description: "A mitochondria-targeted antioxidant peptide studied for its role in oxidative-stress and cellular-aging research.",
    tags: { antiaging: 2, recovery: 1 },
    sizes: [
      { code: "2S10", spec: "10mg/vial", price: 9 },
      { code: "2S50", spec: "50mg/vial", price: 28 },
    ],
  },
  {
    id: "bpc-157",
    name: "BPC-157",
    icon: "🩹",
    tagline: "Tissue & gut recovery support",
    description: "A synthetic peptide fragment widely studied in animal models for its role in supporting tissue repair and gastrointestinal integrity.",
    tags: { recovery: 3, muscle: 1 },
    sizes: [
      { code: "BC5", spec: "5mg/vial", price: 6 },
      { code: "BC10", spec: "10mg/vial", price: 9 },
      { code: "BC20", spec: "20mg/vial", price: 13 },
    ],
  },
  {
    id: "tb-500",
    name: "TB-500",
    icon: "🔧",
    tagline: "Flexibility & recovery research",
    description: "A synthetic version of Thymosin Beta-4 (B4 Acetate), studied for its potential role in cell migration and recovery-related research models.",
    tags: { recovery: 3, muscle: 1 },
    sizes: [
      { code: "TB5", spec: "5mg/vial", price: 17 },
      { code: "TB10", spec: "10mg/vial", price: 26 },
    ],
  },
  {
    id: "bb-blend-10",
    name: "BPC/TB-500 Blend 10mg",
    icon: "🩹",
    tagline: "Combined recovery research blend",
    description: "A combined-dose research blend of BPC-157 (5mg) and TB-500 (5mg) for recovery-focused research.",
    tags: { recovery: 3 },
    sizes: [{ code: "BB10", spec: "10mg/vial (BPC 5mg + TB-500 5mg)", price: 18 }],
  },
  {
    id: "bb-blend-20",
    name: "BPC/TB-500 Blend 20mg",
    icon: "🩹",
    tagline: "Combined recovery research blend",
    description: "A higher-dose research blend of BPC-157 (10mg) and TB-500 (10mg) for recovery-focused research.",
    tags: { recovery: 3 },
    sizes: [{ code: "BB20", spec: "20mg/vial (BPC 10mg + TB-500 10mg)", price: 29 }],
  },
  {
    id: "wolverine-blend",
    name: "Wolverine Blend (KLOW)",
    icon: "🐺",
    tagline: "Recovery + skin research blend",
    description: "A research blend combining KPV (10mg), BPC-157 (10mg), TB-500 (10mg) and GHK-Cu (50mg) for combined recovery and tissue research.",
    tags: { recovery: 3, skin: 1 },
    sizes: [{ code: "BBK80", spec: "80mg/vial (KPV 10mg + BPC 10mg + TB-500 10mg + GHK-Cu 50mg)", price: 33 }],
  },
  {
    id: "recovery-glow-blend",
    name: "GLOW Recovery Blend",
    icon: "✨",
    tagline: "Recovery + skin research blend",
    description: "A research blend combining BPC-157 (10mg), TB-500 (10mg) and GHK-Cu (50mg) for combined recovery and skin research.",
    tags: { recovery: 3, skin: 2 },
    sizes: [{ code: "BBG70", spec: "70mg/vial (BPC 10mg + TB-500 10mg + GHK-Cu 50mg)", price: 30 }],
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    icon: "✨",
    tagline: "Skin, hair & collagen research",
    description: "A copper peptide complex studied extensively for its role in skin remodeling, collagen synthesis, and hair follicle research.",
    tags: { skin: 3, antiaging: 2 },
    sizes: [
      { code: "CU50", spec: "50mg/vial", price: 6 },
      { code: "CU100", spec: "100mg/vial", price: 8 },
    ],
  },
  {
    id: "glutathione",
    name: "Glutathione",
    icon: "🛡️",
    tagline: "Antioxidant & immune research",
    description: "A master antioxidant studied for its role in oxidative-stress reduction, detoxification, and immune-support research.",
    tags: { skin: 1, immune: 2 },
    sizes: [{ code: "GT600", spec: "600mg/vial", price: 7 }],
  },
  {
    id: "kpv",
    name: "KPV",
    icon: "🛡️",
    tagline: "Anti-inflammatory research",
    description: "A tripeptide fragment of alpha-MSH studied for its anti-inflammatory properties in gut and skin research models.",
    tags: { recovery: 1, immune: 1 },
    sizes: [
      { code: "KPV5", spec: "5mg/vial", price: 8 },
      { code: "KPV10", spec: "10mg/vial", price: 9 },
    ],
  },
  {
    id: "snap-8",
    name: "Snap-8",
    icon: "✨",
    tagline: "Anti-wrinkle skin research",
    description: "A synthetic octapeptide studied topically for its effects on expression-line and skin-texture research.",
    tags: { skin: 2 },
    sizes: [{ code: "NP8-10", spec: "10mg/vial", price: 6 }],
  },
  {
    id: "melanotan-1",
    name: "Melanotan I",
    icon: "☀️",
    tagline: "Pigmentation research",
    description: "An alpha-MSH analog studied for its role in melanogenesis and pigmentation research.",
    tags: { skin: 2 },
    sizes: [{ code: "MT1", spec: "10mg/vial", price: 6 }],
  },
  {
    id: "melanotan-2",
    name: "Melanotan II",
    icon: "☀️",
    tagline: "Pigmentation research",
    description: "A synthetic analog of alpha-MSH studied for its role in melanogenesis and pigmentation research.",
    tags: { skin: 2 },
    sizes: [{ code: "MT2", spec: "10mg/vial", price: 7 }],
  },
  {
    id: "hair-skin-nails-blend",
    name: "Healthy Hair, Skin & Nails Blend",
    icon: "💅",
    tagline: "B-vitamin & biotin research blend",
    description: "A B-vitamin blend (niacinamide, thiamine, pantothenic acid, choline, inositol, niacin, biotin, folic acid, riboflavin) studied for hair, skin and nail research.",
    tags: { skin: 3 },
    sizes: [{ code: "HHB", spec: "10mg/vial", price: 11 }],
  },
  {
    id: "semax",
    name: "Semax",
    icon: "🧠",
    tagline: "Mental clarity & focus research",
    description: "A synthetic peptide derived from ACTH, studied for nootropic and neuroprotective properties in cognitive research.",
    tags: { cognitive: 3, stress: 1 },
    sizes: [
      { code: "XA10", spec: "10mg/vial", price: 6 },
      { code: "XA30", spec: "30mg/vial", price: 15 },
    ],
  },
  {
    id: "selank",
    name: "Selank",
    icon: "🧘",
    tagline: "Calm focus & stress research",
    description: "A synthetic peptide analog studied for anxiolytic-like effects and modulation of stress response in research models.",
    tags: { stress: 3, cognitive: 1 },
    sizes: [
      { code: "SK10", spec: "10mg/vial", price: 6 },
      { code: "SK30", spec: "30mg/vial", price: 15 },
    ],
  },
  {
    id: "kisspeptin-10",
    name: "Kisspeptin-10",
    icon: "🧬",
    tagline: "Neuroendocrine research",
    description: "A neuropeptide studied for its role in neuroendocrine and reproductive-axis research models.",
    tags: { antiaging: 1 },
    sizes: [{ code: "KS-10", spec: "10mg/vial", price: 11 }],
  },
  {
    id: "relaxation-blend",
    name: "Relaxation Blend",
    icon: "🌙",
    tagline: "Sleep & calm research blend",
    description: "A blend of GABA (100mg), melatonin (1mg), arginine (100mg) and glutamine (25mg) studied for sleep and relaxation research.",
    tags: { sleep: 3, stress: 2 },
    sizes: [{ code: "RP226", spec: "10mg/vial", price: 11 }],
  },
  {
    id: "cjc-1295",
    name: "CJC-1295 (no DAC)",
    icon: "🏋️",
    tagline: "Muscle & recovery research",
    description: "A growth-hormone releasing hormone analog studied for sustained effects on growth hormone pulses in research settings.",
    tags: { muscle: 3, recovery: 1 },
    sizes: [{ code: "CJC10", spec: "10mg/vial", price: 19 }],
  },
  {
    id: "cjc-ipamorelin-blend",
    name: "CJC-1295 / Ipamorelin Blend",
    icon: "🏋️",
    tagline: "Combined GH-research blend",
    description: "A combined-dose research blend of CJC-1295 without DAC (5mg) and Ipamorelin (5mg) for growth-hormone axis research.",
    tags: { muscle: 3, sleep: 1 },
    sizes: [{ code: "CP10", spec: "10mg/vial (CJC-1295 5mg + Ipamorelin 5mg)", price: 19 }],
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    icon: "💪",
    tagline: "Lean muscle & GH research",
    description: "A selective growth-hormone secretagogue studied for its targeted effects with minimal impact on other hormones in research models.",
    tags: { muscle: 3, sleep: 1, recovery: 1 },
    sizes: [{ code: "IP10", spec: "10mg/vial", price: 9 }],
  },
  {
    id: "lipo-c",
    name: "Lipo-C",
    icon: "🔥",
    tagline: "Lipotropic metabolism research",
    description: "A lipotropic compound blend studied for its role in fat-metabolism research.",
    tags: { weight: 2 },
    sizes: [{ code: "LC120", spec: "10ml vial", price: 10 }],
  },
  {
    id: "lipo-c-fatblaster",
    name: "Lipo-C (FatBlaster)",
    icon: "🔥",
    tagline: "Lipotropic metabolism research",
    description: "A lipotropic blend of L-carnitine, methionine, inositol, choline, B12, B6 and NADH studied for fat-metabolism research.",
    tags: { weight: 2 },
    sizes: [{ code: "LC526", spec: "10ml vial", price: 10 }],
  },
  {
    id: "lipo-c-b12",
    name: "Lipo-C with B12",
    icon: "🔥",
    tagline: "Lipotropic metabolism research",
    description: "A lipotropic blend of L-carnitine, L-arginine, methionine, inositol, choline, B6, B5 and B12 studied for fat-metabolism research.",
    tags: { weight: 2 },
    sizes: [{ code: "LC216", spec: "10ml vial", price: 10 }],
  },
  {
    id: "l-carnitine",
    name: "L-Carnitine",
    icon: "🔥",
    tagline: "Fat-metabolism research",
    description: "An amino-acid derivative studied for its role in fatty-acid transport and energy-metabolism research.",
    tags: { weight: 2, muscle: 1 },
    sizes: [
      { code: "LC600", spec: "10ml vial", price: 10 },
      { code: "LC1200", spec: "10ml vial", price: 12 },
    ],
  },
  {
    id: "super-human-blend",
    name: "Super Human Blend",
    icon: "💪",
    tagline: "Performance amino-acid research",
    description: "An amino-acid blend (arginine, ornithine, citrulline, lysine, glutamine, proline, taurine, carnitine, NAC) studied for performance and recovery research.",
    tags: { muscle: 2, recovery: 1 },
    sizes: [{ code: "SHB", spec: "10ml vial", price: 10 }],
  },
];

const CATEGORY_LABELS = {
  recovery: "Recovery",
  muscle: "Muscle & Performance",
  antiaging: "Anti-Aging",
  cognitive: "Cognitive Focus",
  skin: "Skin & Hair",
  weight: "Weight Management",
  sleep: "Sleep",
  stress: "Stress & Mood",
  immune: "Immune Support",
};

function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}

function getSize(product, code) {
  return product.sizes.find((s) => s.code === code);
}

function cheapestSize(product) {
  return product.sizes.reduce((min, s) => (s.price < min.price ? s : min), product.sizes[0]);
}

function formatPrice(n) {
  return "$" + n.toFixed(2) + " AUD";
}
