// Google Apps Script auto-responder for an existing Gmail inbox.
// No new accounts needed — runs entirely inside your Google account, for free.
//
// Setup: see automation/README.md, "Gmail auto-responder" section.

// ---- Edit this section to customize ----

const YOUR_BUSINESS_NAME = "JaxTrades";

const FAQ_RULES = [
  {
    keywords: ["hour", "open", "closed"],
    reply:
      "We're open Mon-Fri 9am-5pm ET. Outside those hours we'll get back to you as soon as we're back.",
  },
  {
    keywords: ["ship", "delivery"],
    reply:
      "Orders ship within 1-2 business days and typically arrive in 2-5 business days depending on location.",
  },
  {
    keywords: ["track", "status"],
    reply:
      "You can find your order status in the confirmation email we sent when you checked out. If you can't locate it, reply with your order number and we'll look it up.",
  },
  {
    keywords: ["refund", "return"],
    reply:
      "For refunds or returns, reply with your order number and the reason and our team will follow up with next steps.",
  },
];

const FALLBACK_BODY =
  "Thanks for reaching out! This is an automated confirmation that we received your email. " +
  "A team member will reply personally during business hours (Mon-Fri 9am-5pm ET).";

const BUSINESS_HOURS = {
  timezone: "America/New_York",
  days: { 0: null, 1: [9, 17], 2: [9, 17], 3: [9, 17], 4: [9, 17], 5: [9, 17], 6: null },
};

// ---- Core logic (shouldn't need editing) ----

const LABEL_NAME = "AutoReplied";
const MAX_THREADS_PER_RUN = 20;

function autoReplyToNewEmails() {
  const label = getOrCreateLabel_(LABEL_NAME);
  const myEmail = Session.getActiveUser().getEmail();

  const threads = GmailApp.search(
    `is:unread -label:${LABEL_NAME} -in:chats -in:drafts -category:promotions -category:social -category:forums`,
    0,
    MAX_THREADS_PER_RUN
  );

  threads.forEach((thread) => {
    const messages = thread.getMessages();
    const lastMsg = messages[messages.length - 1];

    if (lastMsg.isDraft()) return;
    if ((lastMsg.getFrom() || "").indexOf(myEmail) !== -1) return; // don't reply to yourself
    if (isAutoGenerated_(lastMsg)) return; // avoid bounce/loop with other autoresponders

    const subject = lastMsg.getSubject() || "";
    const body = lastMsg.getPlainBody() || "";
    const faqReply = matchFaq_(`${subject} ${body}`);
    const replyBody = faqReply
      ? faqReply
      : `${FALLBACK_BODY}\n\n${businessHoursNote_()}`;

    thread.reply(`${replyBody}\n\n— ${YOUR_BUSINESS_NAME} (automated reply)`);
    thread.addLabel(label);
  });
}

function matchFaq_(text) {
  const lower = text.toLowerCase();
  for (const rule of FAQ_RULES) {
    if (rule.keywords.some((kw) => lower.includes(kw))) {
      return rule.reply;
    }
  }
  return null;
}

function businessHoursNote_() {
  const tz = BUSINESS_HOURS.timezone;
  const now = new Date();
  const local = new Date(now.toLocaleString("en-US", { timeZone: tz }));
  const hours = BUSINESS_HOURS.days[local.getDay()];
  const open = hours && local.getHours() >= hours[0] && local.getHours() < hours[1];
  return open
    ? "We're open now and will get back to you shortly."
    : "We're currently outside business hours and will reply when we're back.";
}

function isAutoGenerated_(message) {
  const raw = message.getRawContent();
  if (/precedence:\s*(bulk|auto_reply|list)/i.test(raw)) return true;
  if (/auto-submitted:\s*auto-/i.test(raw)) return true;
  if (/no-?reply@/i.test(message.getFrom())) return true;
  return false;
}

function getOrCreateLabel_(name) {
  return GmailApp.getUserLabelByName(name) || GmailApp.createLabel(name);
}

// One-time setup: run this once from the Apps Script editor (Run > createTimeTrigger)
// to schedule autoReplyToNewEmails to check your inbox every 10 minutes.
function createTimeTrigger() {
  // Avoid creating duplicate triggers if run more than once.
  ScriptApp.getProjectTriggers().forEach((t) => {
    if (t.getHandlerFunction() === "autoReplyToNewEmails") ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger("autoReplyToNewEmails").timeBased().everyMinutes(10).create();
}
